version: '3'

services:
  weather-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=wsgi.py
      - WEATHER_API_KEY=0f595912d5a8bd80b773dcb4d3828a8b
    command: flask run --host=0.0.0.0 --port=8080