version: '3'

services:
  weather-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=wsgi.py
      - WEATHER_API_KEY=your_actual_api_key_here
    command: flask run --host=0.0.0.0 --port=8080
